### ISSUE TITLE
StartSpan & EndSpan from within different Threads

### ISSUE THREAD

**Issue by sebastian-garn** [GoogleCloudPlatform/cloud-trace-java#85]
Hi,

my plan is to integrate tracing into our existing backend. All the request handling is currently accomplished by a chain of CompletionStages. My intention now was to simply hook in the tracing by wrapping the existing chains like shown below (exemplary!):

```
  CompletableFuture.runAsync(() -> {
      // tracer.startSpan("abc");
  }, tracerPool)
  .thenCompose(x -> {
      return completionStage; // <-- stuff to measure
  })
  .thenApplyAsync(result -> {
      // tracer.endSpan(traceContextChild);
      return result;
  }, tracerPool)
```

What might happen over here is that startSpan and endSpan get executed in different threads. But since the information about the last context is stored within a thread local variable, stopping the span will fail with the following error:

```
Context was not attached when detaching
java.lang.Throwable
  at io.grpc.Context.detach(Context.java:353)
  at com.google.cloud.trace.GrpcSpanContextHandler$GrpcSpanContextHandle.detach(GrpcSpanContextHandler.java:64)
  at com.google.cloud.trace.SpanContextHandlerTracer.endSpan(SpanContextHandlerTracer.java:92)
``` 

Do I miss something?

**Comment by danielcompton** [comment]
This looks like it will be a blocker for us, as we're using Netty for web requests.

**Comment by jstjohn** [comment]
FYI in another project I have a solution to this issue. 

Basically the problem is that https://github.com/GoogleCloudPlatform/cloud-trace-java/blob/master/sdk/implementation/src/main/java/com/google/cloud/trace/GrpcSpanContextHandler.java uses a threadlocal way of simply storing and returning the current `SpanContext` across scopes. If you use scoping to know which spanContext should be used as current when you call EndSpan etc, you can write a very simple implementation of `SpanContextHandler` that just stores the current SpanContext and returns it when asked. For the `attach` command you just update the context stored by that class, and return a `new DetachedSpenContextHandler` with that SpanContext.

What I do then is I create a new `SpanContextHandler` (using my new "simple" version described above rather than the GRPC one) as well as `SpanContextHandlerTracer`. You can set the parent span and pass that into your `SimpleSpanContextHandler` and then when you call `startSpan` on the `SpanContextHandlerTracer` you get appropriate nesting. 

Documentation etc sucks, it took me a long time and a lot of reading through code and understanding how the various wrappers work to figure this out. I don't know that this is the best solution but it worked for me in a threaded context (in akka-http/scala even).

**Comment by adriancole** [comment]
Might consider census and/or its instrumentation agent?
https://github.com/census-instrumentation/opencensus-java/tree/master/contrib/agent

**Comment by nha** [comment]
@adriancole  Does opencensus java support async? I've been looking for a solution too https://stackoverflow.com/q/53238493/1327651

**Comment by bogdandrutu** [comment]
Hi @nha,

In OpenCensus we have a concept of context independent of the "Span" or "Tags". It represents a Map<key, value> that is propagated with the request (it is implemented as a thread-local so in sync calls automatically gets propagated). For callbacks/async calls just for propagation (we are using io.grpc.Context as the implementation of the context) use the wrap functions defined here https://github.com/grpc/grpc-java/blob/master/context/src/main/java/io/grpc/Context.java#L589.  This will ensure just the context propagation, so entries in the context map will be propagated between different threads.

If you want to start a Span in one thread and end it in a different thread, use the `withSpan` methods from the tracer https://www.javadoc.io/doc/io.opencensus/opencensus-api/0.17.0 :
```java
class MyClass {
  private static Tracer tracer = Tracing.getTracer();
  void handleRequest(Executor executor) {
    Span span = tracer.spanBuilder("MyRunnableSpan").startSpan();
    // do some work before scheduling the async
    executor.execute(Context.wrap(tracer.withSpan(span, new Runnable() {
      @Override      
      public void run() {
        try {
          sendResult();
        } finally {
          span.end();
        }
      }
    })));
  }
}
```

A bit more information about this here https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Span.md#span-creation

**Comment by ruchirsachdeva** [comment]
@bogdandrutu 
I am using java 8 's 
CompletionStage<U> thenComposeAsync (Function<? super T, ? extends CompletionStage<U>> fn);
How can I trace the the passed function using Context.wrap withSpan such that the parent span is maintained across different threads ?

**Comment by bogdandrutu** [comment]
@ruchirsachdeva can you open an issue in the OpenCensus Java repo?

**Comment by codefromthecrypt** [comment]
side comment for your future issue in census


future tracking is trickier than it looks. I think @sjoerdtalsma probably
has nightmares from doing this, I'd bet :P
https://github.com/talsma-ict/context-propagation

**Comment by sjoerdtalsma** [comment]
@adriancole indeed. Even determining _logical_ behaviour is tricky. When combining two futures that both have context, which context applies to the combine function?

I went for the context from the ‘this’ future. 

See ContextAwareCompletabeFuture in the above library and test class to get an idea how tricky this is indeed. 

I have no fond memories of tackling the CompletionStages, but we do have something that seems workable.

**Comment by ruchirsachdeva** [comment]
I added the feature request in opencensus-java repo
https://github.com/census-instrumentation/opencensus-java/issues/1949
