### ISSUE TITLE
stackdriver-trace-api samples could be more close to real use?

### ISSUE THREAD

**Issue by FabianIB** [GoogleCloudPlatform/cloud-trace-java#91]
https://github.com/GoogleCloudPlatform/cloud-trace-java/blob/2e5dac3968380fb40925d76fa6567434c062d8af/samples/stackdriver-trace-api/src/main/java/com/google/cloud/trace/samples/stackdriver/api/StackdriverTraceApi.java#L27

Hi there!

I'm trying to re-implement the tracing capabilities of one of our micro-services, we are currently using google-api-services-cloudtrace, and want to migrate to this SDK, but it has been kind of hard to get this SDK working properly, surerly due to my lack of knowledge on it.

I'm facing two issues:
- I got a service operation that I want to trace, first call to the operation doesn't throw any exceptions, but subsequent calls to the service operation throw: "Trace service is already initialized.".
- Second, as part of our topology, we are using NGINX/sidecar SSL in between our client and the micro service (Jetty), running under that topology, the codes throws this exception:
`java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:159)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:525)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:518)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:457)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:326)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:315)
	at com.google.cloud.trace.grpc.v1.GrpcTraceConsumer.create(GrpcTraceConsumer.java:68)
	at com.google.cloud.trace.service.TraceGrpcApiService.<init>(TraceGrpcApiService.java:162)
	at com.google.cloud.trace.service.TraceGrpcApiService.<init>(TraceGrpcApiService.java:43)
	at com.google.cloud.trace.service.TraceGrpcApiService$Builder.build(TraceGrpcApiService.java:141)
	at com.llbean.purchase.history.producer.util.CloudTraceHelper.createTrace(CloudTraceHelper.java:43)
	at com.llbean.purchase.history.producer.rest.InitiationResource$1.run(InitiationResource.java:76)
	at java.lang.Thread.run(Thread.java:748)`
in our local development environment we don't have NGINX in between, and the error isn't present.  Wondering if we should add any other jar to the gradle file? currently we have this:
```
compile 'com.google.cloud.trace:trace-grpc-api-service:0.4.0'
compile 'com.google.cloud.trace:core:0.4.0'
compile 'com.google.auth:google-auth-library-oauth2-http:0.7.1'
compile 'io.grpc:grpc-netty:1.6.1'	
compile 'io.netty:netty-tcnative-boringssl-static:2.0.5.Final'
```

So based on this I think the sample is too far away from a simple use case.  Could you please help me to understand how this sample could be implemented in a real scenario?

Thanks a lot! 
-F

**Comment by FabianIB** [comment]
I already figured out what was the issue... it has to do with using **netty-tcnative-boringssl-static version 2.0.6.Final**, if I change that to 2.0.5.Final, it works just fine.
